### ISSUE TITLE
macOS 菜单栏汉化

### ISSUE THREAD

**Issue by RA1NO3O** [sollyu/AndroidStudioChineseLanguagePack#1]
<img width="1512" alt="截屏2024-05-30 10 59 57" src="https://github.com/sollyu/AndroidStudioChineseLanguagePack/assets/25654559/e6f7c173-edcf-4865-ac35-375fcef1429a">
菜单栏的汉化怎么是Windows那套风格草哈哈哈哈

**Comment by sollyu** [comment]
这是你的个人设置的问题吧，改变一下主题看看，我这里最新的release是没问题的，下面是预览图：
![image](https://github.com/sollyu/AndroidStudioChineseLanguagePack/assets/43105186/1b7a342f-1dbf-4409-813d-d0774b77e045)

**Comment by RA1NO3O** [comment]
抱歉我没说清楚，我的意思是macOS的菜单栏应该没有"(F)" "(E)"这些源自Windows的Alt快捷键提示才对吧

**Comment by sollyu** [comment]
好像是，不过也没啥影响，晚会更新到最新的版本试试。

**Comment by sollyu** [comment]
刚测试了最新版本的，也有这个问题，不过这个也不是我能搞定的，先关闭issue了。
